/**
 * API client module — single source of truth for all backend communication.
 *
 * Design decisions:
 * 1. Idempotency keys are generated HERE (client-side UUID) and stored in
 *    sessionStorage tied to the form submission attempt. On page refresh,
 *    a new key is generated — correct because a refresh means user intent
 *    to submit a new expense. A retry of the SAME submission reuses the key.
 *
 * 2. All monetary amounts are sent as strings to avoid any JS float issues
 *    before the data reaches the API (even though the API also validates).
 *
 * 3. AbortController is used to cancel in-flight requests when the component
 *    unmounts or the user navigates away.
 */

const API_BASE = 'http://localhost:3001';

/**
 * Creates an expense with idempotency protection.
 * @param {object} data - { amount, category, description, expense_date }
 * @param {string} idempotencyKey - UUID generated by the caller for this attempt
 * @param {AbortSignal} [signal] - Optional abort signal
 * @returns {Promise<{ expense: object, created: boolean }>}
 */
export async function createExpense(data, idempotencyKey, signal) {
  const response = await fetch(`${API_BASE}/expenses`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Idempotency-Key': idempotencyKey,
    },
    body: JSON.stringify(data),
    signal,
  });

  const json = await response.json();

  if (!response.ok) {
    const error = new Error(json.error || 'Failed to create expense');
    error.details = json.details || [];
    error.status = response.status;
    throw error;
  }

  return { expense: json.expense, created: response.status === 201 };
}

/**
 * Fetch expenses with optional filtering and sorting.
 * @param {{ category?: string, sort?: string }} params
 * @param {AbortSignal} [signal]
 * @returns {Promise<{ expenses: object[], totalFormatted: string, totalCents: number }>}
 */
export async function fetchExpenses({ category, sort } = {}, signal) {
  const params = new URLSearchParams();
  if (category && category !== 'all') params.set('category', category);
  if (sort) params.set('sort', sort);

  const url = `${API_BASE}/expenses${params.toString() ? '?' + params.toString() : ''}`;

  const response = await fetch(url, { signal });
  const json = await response.json();

  if (!response.ok) {
    throw new Error(json.error || 'Failed to fetch expenses');
  }

  return json;
}

/**
 * Fetch category-wise spending summary.
 * @param {AbortSignal} [signal]
 * @returns {Promise<{ summary: Array }>}
 */
export async function fetchCategorySummary(signal) {
  const response = await fetch(`${API_BASE}/expenses/summary`, { signal });
  const json = await response.json();

  if (!response.ok) {
    throw new Error(json.error || 'Failed to fetch summary');
  }

  return json;
}
